# Generated by Django 5.1.4 on 2025-01-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_color_size_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
